config/routes.rb
Calendar::Application.routes.draw do
  resources :plans 
  resources :lessons
  resources :report
  resources :titul
  resources :reportn

root :to => "plans#index"

match 'local_lessons/:plan_id' => 'Lessons#index', :as => 'local_lessons'
match 'new_lesson_path/:plan_id' => 'Lessons#new', :as => 'new_lesson' 

match 'local_report/:id' => 'Report#report', :as => 'local_report' 
match 'local_titul/:id' => 'Titul#titul', :as => 'local_titul'
match 'local_reportn/:id' => 'Reportn#reportn', :as => 'local_reportn'

   

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	scope :desc_scope, order: "id desc"
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	has_many :lessons

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  # GET /lessons
  # GET /lessons.json
 



  def index
if params[:plan_id]
@lessons = Lesson.where(:plan_id => params[:plan_id])
@plan_id=params[:plan_id]
else
@lessons = Lesson.all
end
  respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons;@plan_id }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @plan_id= params[:plan_id]
    @lesson = Lesson.new
    @lesson.plan_id=@plan_id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson;@plan_id}
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        plan_id=@lesson.plan_id
        format.html { redirect_to local_lessons_path(plan_id)}
        format.json { head :no_content}
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @plan_id=@lesson.plan_id
     @lesson.destroy

    respond_to do |format|
      format.html { redirect_to local_lessons_path(@plan_id) }
      format.json { head :no_content }
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  # GET /plans
  # GET /plans.json

 
 

  def index
    @plans = Plan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to plans_url }
        format.json { head :no_content}
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
 
def report

    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
    end
  end



end

app/controllers/reportn_controller.rb
class ReportnController < ApplicationController
 
def reportn

    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
    end
  end



end

app/controllers/titul_controller.rb
class TitulController < ApplicationController
 
def titul

    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/plans_helper.rb
module PlansHelper


	
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>

<%= link_to "My Blog", plans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
<%= javascript_include_tag "bootstrap/bootstrap" %>
<%= javascript_include_tag "bootstrap/bootstrap.min" %>
      <%= stylesheet_link_tag 'bootstrap/css/bootstrap.css' %>
      <%= stylesheet_link_tag 'bootstrap/css/bootstrap.min.css' %>
      <%= stylesheet_link_tag 'bootstrap/css/bootstrap.min.css' %>

<%= stylesheet_link_tag 'bootstrap/css/bootstrap-responsive.css' %>

<%= stylesheet_link_tag 'bootstrap/css/bootstrap-responsive.min.css' %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :lesson_number %><br />
    <%= f.number_field :lesson_number %>
  </div>
  <div class="field">
    <%= f.label :part_name %><br />
    <%= f.text_field :part_name %>
  </div>
  <div class="field">
    <%= f.label :weeks_number %><br />
    <%= f.number_field :weeks_number %>
  </div>
  <div class="field">
    <%= f.label :hours_count %><br />
    <%= f.number_field :hours_count %>
  </div>
  <div class="field">
    <%= f.label :lesson_type %><br />
    <%= f.text_field :lesson_type %>
  </div>
  <div class="field">
    <%= f.label :manual %><br />
    <%= f.text_field :manual %>
  </div>
  <div class="field">
    <%= f.label :student_tasks %><br />
    <%= f.text_field :student_tasks %>
  </div>
  <div class="field">
    <%= f.label :student_homeworks %><br />
    <%= f.text_field :student_homeworks %>
  </div>
  <div class="field">
    <%= f.label :plan_id %><br />
    <%= f.number_field :plan_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<table class="table table-striped table-bordered table-condensed" style="margin-top:10px;">
  <tr>
    <th>№ урока</th>
    <th>Наименование разделов и тем</th>
    <th>Номера недель</th>
    <th>Кол-во часов</th>
    <th>Вид занятий</th>
    <th>Наглядные пособия</th>
    <th>Задания для студентов</th>
    <th>Самостоятельная работа для студентов</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lessons.each do |lesson| %>
  <tr>
    <td><%= lesson.lesson_number %></td>
    <td><%= lesson.part_name %></td>
    <td><%= lesson.weeks_number %></td>
    <td><%= lesson.hours_count %></td>
    <td><%= lesson.lesson_type %></td>
    <td><%= lesson.manual %></td>
    <td><%= lesson.student_tasks %></td>
    <td><%= lesson.student_homeworks %></td>
    <td><%= link_to 'Открыть', lesson %></td>
    <td><%= link_to 'Редактировать', edit_lesson_path(lesson) %></td>
    <td><%= link_to 'Удалить', lesson, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Вернуться к планам', plans_path %> | <%= link_to 'Добавить новый урок', new_lesson_path(@plan_id) %>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>Lesson number:</b>
  <%= @lesson.lesson_number %>
</p>

<p>
  <b>Part name:</b>
  <%= @lesson.part_name %>
</p>

<p>
  <b>Weeks number:</b>
  <%= @lesson.weeks_number %>
</p>

<p>
  <b>Hours count:</b>
  <%= @lesson.hours_count %>
</p>

<p>
  <b>Lesson type:</b>
  <%= @lesson.lesson_type %>
</p>

<p>
  <b>Manual:</b>
  <%= @lesson.manual %>
</p>

<p>
  <b>Student tasks:</b>
  <%= @lesson.student_tasks %>
</p>

<p>
  <b>Student homeworks:</b>
  <%= @lesson.student_homeworks %>
</p>

<p>
  <b>Plan:</b>
  <%= @lesson.plan_id %>
</p>


<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', local_lessons_path(@lesson.plan_id) %>

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :predmet %><br />
    <%= f.text_field :predmet %>
  </div>
  <div class="field">
    <%= f.label :prepod %><br />
    <%= f.text_field :prepod %>
  </div>
  <div class="field">
    <%= f.label :spec %><br />
    <%= f.text_field :spec %>
  </div>
  <div class="field">
    <%= f.label :grups %><br />
    <%= f.text_field :grups %>
  </div>
  <div class="field">
    <%= f.label :kurs %><br />
    <%= f.text_field :kurs %>
  </div>
  <div class="field">
    <%= f.label :semestr %><br />
    <%= f.text_field :semestr %>
  </div>
  <div class="field">
    <%= f.label :god %><br />
    <%= f.text_field :god %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br />
    <%= f.text_field :accepted %>
  </div>
  <div class="field">
    <%= f.label :week_count %><br />
    <%= f.number_field :week_count %>
  </div>
  <div class="field">
    <%= f.label :lecture_count %><br />
    <%= f.number_field :lecture_count %>
  </div>
  <div class="field">
    <%= f.label :labs_count %><br />
    <%= f.number_field :labs_count %>
  </div>
  <div class="field">
    <%= f.label :kurs_project %><br />
    <%= f.number_field :kurs_project %>
  </div>
  <div class="field">
    <%= f.label :itself_load %><br />
    <%= f.number_field :itself_load %>
  </div>
  <div class="field">
    <%= f.label :literature %><br />
    <%= f.text_field :literature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1 style="padding-bottom:50px;">Управление календарными планами</h1>


<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">
   <% @plans.each do |plan| %>
    <%if (plan==@plans.first)%>
    <li class="active"><a href="#<%= plan.id %>" data-toggle="tab"><%= plan.predmet %></a></li>
      <%else%>
        <li class=""><a href="#<%= plan.id %>" data-toggle="tab"><%= plan.predmet %></a></li>
            <%end%>
         <% end %>
        </ul>
        <div class="tab-content">
          <% @plans.each do |plan| %>
        <%if (plan==@plans.first)%>
          
 <div class="tab-pane active" id='<%= plan.id %>'>
         <%else%>
          <div class="tab-pane" id='<%= plan.id %>'>
 <%end%>
        
        
        
          <table class="table table-striped table-bordered table-condensed" style="width:70%;font-size:10px;">
             <thead>
  <tr>
    <th>Предмет</th>
    <th>Преподаватель</th>
    <th>Специальность</th>
    <th>Grups</th>
    <th>Курс</th>
    <th>Семестр</th>
    <th>Год</th>
    <th>Утвержден</th>
    <th>Число недель</th>
    <th>Число лекций</th>
    <th>Число лаб.</th>
    <th>Курсовой проект</th>
    <th>Самост. работа</th>
    <th>Литература</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>

 
  <tr >
    <td><%= plan.predmet %></td>
    <td><%= plan.prepod %></td>
    <td><%= plan.spec %></td>
    <td><%= plan.grups %></td>
    <td><%= plan.kurs %></td>
    <td><%= plan.semestr %></td>
    <td><%= plan.god %></td>
    <td><%= plan.accepted %></td>
    <td><%= plan.week_count %></td>
    <td><%= plan.lecture_count %></td>
    <td><%= plan.labs_count %></td>
    <td><%= plan.kurs_project %></td>
    <td><%= plan.itself_load %></td>
    <td><%= plan.literature %></td>
    
    <td> <p><%= link_to "Уроки",local_lessons_path(plan)%></p></td>

    <td><%= link_to 'Открыть', plan %></td>
    <td><%= link_to 'Редактировать', edit_plan_path(plan) %></td>
    <td><%= link_to 'Удалить', plan, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
    </tbody>
 </table>

<%= link_to "Распечатать титульник",local_titul_path(plan)%></p></td>
<%= link_to "Распечтать отчет, четная сторона",local_report_path(plan)%></p></td>

<%= link_to "Распечтать отчет, нечетная сторона",local_reportn_path(plan)%></p></td>

 </div>

 <% end %>     
 </div>
</div>


 

<br />

<%= link_to 'Создать новый план', new_plan_path %>

app/views/plans/new.html.erb
<h1>New plan</h1>
<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Predmet:</b>
  <%= @plan.predmet %>
</p>

<p>
  <b>Prepod:</b>
  <%= @plan.prepod %>
</p>

<p>
  <b>Spec:</b>
  <%= @plan.spec %>
</p>

<p>
  <b>Grups:</b>
  <%= @plan.grups %>
</p>

<p>
  <b>Kurs:</b>
  <%= @plan.kurs %>
</p>

<p>
  <b>Semestr:</b>
  <%= @plan.semestr %>
</p>

<p>
  <b>God:</b>
  <%= @plan.god %>
</p>

<p>
  <b>Accepted:</b>
  <%= @plan.accepted %>
</p>

<p>
  <b>Week count:</b>
  <%= @plan.week_count %>
</p>

<p>
  <b>Lecture count:</b>
  <%= @plan.lecture_count %>
</p>

<p>
  <b>Labs count:</b>
  <%= @plan.labs_count %>
</p>

<p>
  <b>Kurs project:</b>
  <%= @plan.kurs_project %>
</p>

<p>
  <b>Itself load:</b>
  <%= @plan.itself_load %>
</p>

<p>
  <b>Literature:</b>
  <%= @plan.literature %>
</p>


<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>

app/views/reportn/reportn.html.erb
    <link rel="stylesheet" href="print.css" type="text/css">
    <link rel="stylesheet" href="style.css" type="text/css">
 <a href="#" onclick="print(); return false;" style="font-size:5px;">версия для печати</a>

  <style type="text/css">
    .printdiv{
      font-size:10px; padding-left:15px; padding-top:10px; font-style:italic;
     }
     .printspan{width:90%;font-size:10px;height:11px; }

     .customH3{vertical-align:top;padding-left:25%;font-size:15px;}

     .textdiv{font-size:10px;}
  </style>


<%@nechet=0%>
<%@chet=0%>


<%@lessSize=@plan.lessons.size%>
<%@npageSize=@lessSize/6%>
<%@ourPagesSize=@lessSize/6%><!--общее число страниц-->
<%if !((@lessSize%6).zero?)%>
<%@lastRecSize=@lessSize-(@npageSize*6)%><!--сколько будет печати для последней страницы-->
 <%@npageSize=(@npageSize+1)/2%>   
<%@orPage=  @npageSize%><!--Сколько всего итераций-->

<!--если итераций без остатка (на последней странице 6 записей)-->


<%if@lessSize>=19%>
<%@ourPagesSize=4%>
<%end%>

<%else%>
<%@npageSize=@npageSize/2%>
<%end%>

<!--if firs page size equal 6-->
<%if @lastRecSize==nil%>
<%@lastRecSize=0%>
<%end%>
 
<!--if lessons size <6-->
<%if @npageSize==0%>
<%@npageSize=1%>
<%@orPage=1%>
<%end%>








<%
 
until @npageSize == 0
%>
 




<!--тут забацать цикл while-->
<table style="width:100%">
<tr>
<td valign="top" style="width:50%" >

<%if  @ourPagesSize>=4%>
  <table style="width:50%;"class="table table-striped table-bordered table-condensed"> 
    <tr>
    <th style="height: 100px; width: 5px; font-weight: normal;text-align: center;" >№ урока</th>
    <th style="height: 100px;font-weight: normal; text-align: center;" >Наименование разделов и тем</th>
    <th style="height: 100px; width: 5px;  font-weight: normal; text-align: center;" >Номера недель</th>
    <th style="height: 100px; width: 5px; font-weight: normal;">Колличество часов</th>
    <th style="height: 100px; width: 5px;font-weight: normal; text-align: center;" >Вид занятий</th>
    <th style="height: 100px; width: 5px;font-weight: normal; text-align: center;" >Наглядные пособия</th>
    <!--<th style="height: 50px; width: 5px;font-weight: normal;text-align: center;">Задание для студентов</th>-->
    <th style="height: 100px; width: 5px;font-weight: normal;text-align: center;">Задания</th>
    <th style=" font-weight: normal;text-align: center; width:10px; ">Самостоят.работа</th>
  </tr>

 

 <!--begin (Если первые записи и их не 6 штук)-->
<%if @lastRecSize!=0 and @nechet==0  %>
  <% @plan.lessons.each do |lesson| %>
<%@idx=@plan.lessons.index(lesson)%>
  <%if (@lessSize-@idx<=@lastRecSize)and (@npageSize==@orPage)%><!--если последняя страница-->
    <tr  style="font-size:5px;">
    <td style="font-size:10px;height:50px;"><i><%=lesson.lesson_number%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.part_name%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.weeks_number%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.hours_count%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.lesson_type%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.manual%></i></td>
    <td style="font-size:10px;height:50px"><i><%=lesson.student_tasks%></i></td>
    <td style="font-size:10px; height:50px;"><i><%=lesson.student_homeworks%></i></td>
    </tr>
   <%@nechet=@nechet+1%>
   <%end%>
<%end%>
<%end%>
<!--END-->

<!--begin (Если не первые записи)-->
<%if @lastRecSize==0 and@nechet>0 %>
 <% @plan.lessons.each do |lesson| %>
<%@idx=@plan.lessons.index(lesson)%>
<%if (@nechet>0) and (@idx>@nechet+6)and(@idx<=@nechet+12)%>
  <tr  style="font-size:5px;">
    <td style="font-size:10px;height:50px;"><i><%=lesson.lesson_number%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.part_name%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.weeks_number%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.hours_count%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.lesson_type%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.manual%></i></td>
    <td style="font-size:10px;height:50px"><i><%=lesson.student_tasks%></i></td>
    <td style="font-size:10px; height:50px;"><i><%=lesson.student_homeworks%></i></td>
  </tr>
   <%@nechet=@nechet+1%>
   <%end%>
 <%end%>
  <%end%>
 <!--end-->


<!--begin (Если первые записи и их ровно 6)-->
<%if @lastRecSize==0 and  @nechet==0  %>

 <% tmp_chet=@nechet%>
 <% @plan.lessons.each do |lesson| %>

<%@idx=@plan.lessons.index(lesson)%>
<%if @idx>=(@lessSize-(tmp_chet+6)) and @idx<(@lessSize-tmp_chet)%>
  <tr  style="font-size:5px;">
    <td style="font-size:10px;height:50px;"><i><%=lesson.lesson_number%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.part_name%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.weeks_number%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.hours_count%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.lesson_type%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.manual%></i></td>
    <td style="font-size:10px;height:50px"><i><%=lesson.student_tasks%></i></td>
    <td style="font-size:10px; height:50px;"><i><%=lesson.student_homeworks%></i></td>
  </tr>
   <%@nechet=@nechet+1%>
   <%end%>
 <%end%>
  <%end%>
 <!--end-->

</table>
<%@lastRecSize=0%>
<%@npageSize=@npageSize-1%>
<%end%>
</td>

<!-- (другая сторона)-->
<!-- если уже не первый лист -->


<%if (@npageSize>0)%> <!-- если больше чем 1 лист и больше -->
 <!--another pageside-->
<td valign="top">
  
    <table style="width:50%;" class="table table-striped table-bordered table-condensed"> 
    <tr>
    <th style="height: 100px; width: 5px; font-weight: normal;text-align: center;" >№ урока</th>
    <th style="height: 100px;font-weight: normal; text-align: center;" >Наименование разделов и тем</th>
    <th style="height: 100px; width: 5px;  font-weight: normal; text-align: center;" >Номера недель</th>
    <th style="height: 100px; width: 5px; font-weight: normal;">Колличество часов</th>
    <th style="height: 100px; width: 5px;font-weight: normal; text-align: center;" >Вид занятий</th>
    <th style="height: 100px; width: 5px;font-weight: normal; text-align: center;" >Наглядные пособия</th>
    <!--<th style="height: 50px; width: 5px;font-weight: normal;text-align: center;">Задание для студентов</th>-->
    <th style="height: 100px; width: 5px;font-weight: normal;text-align: center;">Задания</th>
    <th style=" font-weight: normal;text-align: center; width:10px; ">Самостоят.работа</th>
    </tr>
   


<!--begin (Если не первые записи)-->
<%if (@chet>=6)%>
 <% @plan.lessons.each do |lesson| %>
<%@idx=@plan.lessons.index(lesson)%>
<%if (@chet>=0) and (@idx>@chet+6)and(@idx<=@chet+12)%>
  <tr  style="font-size:5px;">
    <td style="font-size:10px;height:50px;"><i><%=lesson.lesson_number%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.part_name%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.weeks_number%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.hours_count%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.lesson_type%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.manual%></i></td>
    <td style="font-size:10px;height:50px"><i><%=lesson.student_tasks%></i></td>
    <td style="font-size:10px; height:50px;"><i><%=lesson.student_homeworks%></i></td>
  </tr>
   <%@chet=@chet+1%>
   <%end%>
 <%end%>
  <%end%>
 <!--end-->


<!--begin (Если первые записи и их ровно 6)-->
<%if @chet==0%>
 <% @plan.lessons.each do |lesson| %>
<%@idx=@plan.lessons.index(lesson)%>
<%if (@chet>=0) and (@chet<=5)%>
  <tr  style="font-size:5px;">
    <td style="font-size:10px;height:50px;"><i><%=lesson.lesson_number%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.part_name%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.weeks_number%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.hours_count%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.lesson_type%></i></td>
    <td style="font-size:10px;height:50px;"><i><%=lesson.manual%></i></td>
    <td style="font-size:10px;height:50px"><i><%=lesson.student_tasks%></i></td>
    <td style="font-size:10px; height:50px;"><i><%=lesson.student_homeworks%></i></td>
  </tr>
   <%@chet=@chet+1%>
   <%end%>
 <%end%>
  <%end%>
 <!--end-->
 </table>
</td>
<%@npageSize=@npageSize-1%>
<%end%> <!-- <if (@npageSize>0)>-->
 
  
</tr>
</table>


 

 
<%end%> <!--конец общего цикла по всем страничкам-->

 

 

 














